android_binary(
  name = 'microbenchmarks',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:18',
  keystore = ':debug_keystore',
  deps = [
    '//java/org/denovogroup/microbenchmarks:microbenchmarks',
    '//res/org/denovogroup/microbenchmarks:res',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':microbenchmarks',
)
